# Generated by Django 2.1.5 on 2019-01-23 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='名前')),
                ('gender', models.CharField(max_length=2, verbose_name='性別')),
                ('age', models.IntegerField(verbose_name='年齢')),
            ],
        ),
    ]
