# Generated by Django 2.1.5 on 2019-01-25 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='title',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(max_length=1, verbose_name='性別'),
        ),
    ]
