# Generated by Django 2.1.5 on 2019-01-26 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_auto_20190125_1346'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(choices=[('英語', '英語'), ('ファイナンス', 'ファイナンス'), ('プログラミング', 'プログラミング')], default='英語', max_length=255, verbose_name='性別')),
                ('lesson_day', models.DateTimeField(verbose_name='受講日')),
                ('lesson_time', models.PositiveIntegerField(verbose_name='受講時間')),
                ('price', models.PositiveIntegerField(verbose_name='支払金額')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exam.Customer')),
            ],
        ),
    ]
