# Generated by Django 2.1.5 on 2019-01-26 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='genre',
            field=models.CharField(choices=[('英語', '英語'), ('ファイナンス', 'ファイナンス'), ('プログラミング', 'プログラミング')], default='英語', max_length=255, verbose_name='ジャンル'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson_time',
            field=models.PositiveIntegerField(verbose_name='受講時間（h）'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='price',
            field=models.IntegerField(null=True, verbose_name='支払金額'),
        ),
    ]
