# Generated by Django 2.1.5 on 2019-01-26 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_auto_20190126_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='lesson_day',
            field=models.DateTimeField(verbose_name='受講日'),
        ),
    ]
