# Generated by Django 2.1.5 on 2019-01-26 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0008_auto_20190126_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='lesson_day',
            field=models.DateField(verbose_name='受講日'),
        ),
    ]
